### ISSUE TITLE
Add demo documentation to demonstrate how to use budget and farming modules

### ISSUE THREAD

**Issue by kogisin** [tendermint/farming#121]
## Summary

The title of the issue is pretty much self-explanatory. This issue requests to add demo documentation that demonstrates how to use both budget and farming modules. One thing to note here is that this demo covers the farming module that F1 rewards distribution is applied. The existing demo inside [docs](https://github.com/tendermint/farming/tree/master/docs) folder should become legacy (this is being handled in #116) once this demo is published. 

## Sources

- [budget module v0.1.0](https://github.com/tendermint/budget/releases/tag/v0.1.0)
- [farming module v0.1.0](https://github.com/tendermint/farming/releases/tag/v0.1.0)

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by dongsam** [comment]
Could you add the doc on `docs/Tutorials/demo/budget_with_farming.md` path? because I pre-linked to [Budget repo](https://github.com/tendermint/budget/blob/master/docs/Tutorials/demo/README.md) to prevent duplicate documents of the budget + farming demo https://github.com/tendermint/budget/pull/39
