### ISSUE TITLE
bug: epoch is being increased multiple times when there is two or more plans sharing same staking coin denom

### ISSUE THREAD

**Issue by hallazzang** [tendermint/farming#126]
## Description

For each `AllocateRewards()` call, the epoch of a staking coin denom should be increased by only 1.
But currently if there are two or more plans sharing same staking coin denom for their staking coin weights,
the epoch is being increased more than 1 times.

## Version

master(60a8fd79abbe34c0b2e57da9710f702bcc437ac6)

**Comment by dongsam** [comment]
Could you add a test code to validate this case does not occur anymore?
I heard you the test code would be included on https://github.com/tendermint/farming/issues/119 right?

**Comment by hallazzang** [comment]
@dongsam Yes I'm adding tests to test if this issue has been resolved
