### ISSUE TITLE
`PlanI` interface should have `GetEpochAmount` and `GetEpochRatio` methods

### ISSUE THREAD

**Issue by hallazzang** [tendermint/farming#215]
Currently `PlanI` doesn't have such methods. To extract `EpochAmount` or `EpochRatio` from a `PlanI`, we need to use type assertion and convert it to `*FixedAmountPlan` or `*RatioPlan`.
The problem is, if we have another type of plan which conforms the `PlanI` interface, we have to add another type assertion branch to get the concrete type.
I think adding `GetEpochAmount` and `GetEpochRatio` to `PlanI` makes more sense here so we don't have to convert an interface variable to a concrete type.
So a `FixedAmountPlan` will return a zero `sdk.Dec{}` for `GetEpochRatio` and a `RatioPlan` will return `nil` for `GetEpochAmount`.

Here's a brief examples.

Currently we should do:
```go
fixedAmountPlan, ok := plan.(*FixedAmountPlan) // plan is a `PlanI` variable
if !ok {
        panic("wrong type")
}
fmt.Println(fixedAmountPlan.EpochAmount) // use `EpochAmount`
```

But we can change it to:
```go
fmt.Println(plan.GetEpochAmount()) // it'll return `nil` for a `RatioPlan`
```

**Comment by dongsam** [comment]
I think the code may be a few lines longer, but the existing method would be more explicit in terms of type and exception handling

**Comment by kogisin** [comment]
I don't have strong opinion on this. But in my opinion the current way to assert type and extract the method makes it more clear although it requires a few more lines long. I think we can come back to this issue if we ever plan to add another type of plan.

**Comment by hallazzang** [comment]
Thank you for your feedbacks. Closing this.
