### ISSUE TITLE
Check the sum of epoch ratio only with plans with overlapping periods

### ISSUE THREAD

**Issue by hallazzang** [tendermint/farming#241]
Currently, period of each plan is not considered when validating the sum of epoch ratio

**Comment by dongsam** [comment]
@hallazzang It would be good to refer to the similar logic that has recently been applied to the budget module, 
https://github.com/tendermint/budget/pull/110/files#diff-ff876dc3a8249f14c0143fa104537298d693e11edee449ecd0e6f13464da5cedR73-L99
This might not be the best way, so if there's a better direction, please give us your opinion.
