### ISSUE TITLE
docs: Swagger specification on web

### ISSUE THREAD

**Issue by hallazzang** [tendermint/farming#38]
Publish the Swagger specification on web

**Comment by dongsam** [comment]
after https://github.com/tendermint/farming/issues/39 merged, Let me publish Swagger via SwaggerHub

**Comment by dongsam** [comment]
https://app.swaggerhub.com/apis/gravity-devs/farming/0.1.0 here is the temporary published swagger page, Let me update after #39 merged.

**Comment by dongsam** [comment]
[Swagger Docs v0.1.2](https://app.swaggerhub.com/apis-docs/gravity-devs/farming/0.1.2#) is published on https://github.com/tendermint/farming/pull/124
