### ISSUE TITLE
Create custom binary or cli for demo

### ISSUE THREAD

**Issue by dongsam** [tendermint/farming#45]
## Summary

Create a branch for custom binary to Every block blocktime is added by one day or Reward happens immediately per every block or add tmporary cli for to run the end-of-epoch logic or add one day for the blockheader for easy to reward distribution demo

## Problem Definition

- We have to MVP version demo, but reward epoch per day is so long time for demo situation

## References

https://github.com/tendermint/farming/issues/43
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hallazzang** [comment]
Alternatively we could add a custom CLI command to run the end-of-epoch logic

**Comment by dongsam** [comment]
Good suggestion, We can add it for testing and then exclude it from the production version.

**Comment by hallazzang** [comment]
Closed via 48f5fac096ca644bb21bb21b6b9286a443e4ff81
