### ISSUE TITLE
Provide sample scripts to demonstrate how to interact with a node using cli commands

### ISSUE THREAD

**Issue by kogisin** [tendermint/farming#46]
## Summary

When developers first come to play with the farming module, they look for a way to bootstrap a node locally and interact with a node using CLI commands and REST APIs. So, providing sample scripts to demonstrate how to interface with a node using CLI commands will increase developer experience. 

## References

- [Sample scripts in liquidity module](https://github.com/tendermint/liquidity/tree/develop/scripts)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dongsam** [comment]
Close it because it can be covered with https://github.com/tendermint/farming/issues/43
