### ISSUE TITLE
Handle plan termination

### ISSUE THREAD

**Issue by hallazzang** [tendermint/farming#53]
- [ ] Send remaining coins in farming pool to termination address
- [ ] Added terminated field on base_plan
- [ ] Update Spec and relevant docs
- [ ] Applies to the cli dependence codes in #51 as well.

**Comment by hallazzang** [comment]
@dongsam @kogisin 
proto3 doesn't support optional scalar field.

**Comment by dongsam** [comment]
> 2. Use `string` and parse it as boolean value only if the string is not empty.

As we discussed offline, let's go with Option 2.
