### ISSUE TITLE
Create farming pool for private plans

### ISSUE THREAD

**Issue by hallazzang** [tendermint/farming#58]
Current implementation uses the farmer's address as the farming pool address, this makes a possibility of an attack: the attacker creates a private plan with their own token which distributes huge farming rewards to make other users to buy that coin and then sends all his/her coins to another address just before the reward distribution happens.

To prevent this kind of attack vector, we should consider creating a farming pool for a private plan and make the creator to send their coins into the pool.
This makes it impossible to send coins from the farming pool to other addresses(unless they find out the private key for that farming pool address, but it's a different problem).

**Comment by dongsam** [comment]
It will be applied on https://github.com/tendermint/farming/pull/77, you can check the bullet points on the PR
