### ISSUE TITLE
Adding farms for liquidity providers

### ISSUE THREAD

**Issue by Dexter696** [tendermint/farming#86]
The Cosmos Hub does not currently support farming incentives.
However, a Cosmos SDK module is currently being developed for this purpose. 
https://github.com/tendermint/farming
The Hub community may submit a proposal to upgrade to the farming module and enable farming incentives for the Gravity DEX. We will report on the readiness of the farming module and the proposal as we get further information.

## Bullet Points

- [ ] 

## References

-
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dongsam** [comment]
Thank you for your interest, we are developing the module for that purpose and will proceed with the Security Audit and submit the Signal Proposal as soon as the code is somewhat complete. After that, if there is no problem, we expect to be included in the Hub through Upgrade Proposal.

**Comment by dongsam** [comment]
Let me close the issue and comment when the governance proposal proceeds.
